# Site settings
title: 0x4E0x650x6F 
description: "0x4E0x650x6F"
baseurl: ""
url: "http://www.tiagoalexandre.com"
#url: "http://127.0.0.1"
timezone: Europe/Lisbon
encoding: utf-8
# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title
safe: true
lsi: false
source: ""
excerpt_separator: "<!-- more -->"
paginate: 13
paginate_path: "/posts/page:num/"
#layout 
username: 0x4E0x650x6F
gems:      [jekyll-paginate]