# Site settings
title: 0x4E0x650x6F 
description: "0x4E0x650x6F"
baseurl: ""
url: "http://www.tiagoalexandre.com"
timezone: Europe/Lisbon
encoding: utf-8
# Build settings
markdown: kramdown
permalink: /:category/:year/:month/:day/:title
safe: true
lsi: false
source: ""
excerpt_separator: "<!-- more -->"
paginate: 1
paginate_path: "/blog/page:num/"
#layout 
username: 0x4E0x650x6F
